### PR TITLE
Ci stuffs

### LINKED ISSUE #4: Set up continuous integration.

### PR DESCRIPTION
**Pull request by Coding-Doctors**
Closes #4 
Example pr with the CI stuffs setup https://github.com/Coding-Doctors/sudobot-rs/pull/1 codecov will add comments on coverage and showup properly once this is merged into master.

### CODE REVIEW

**Comment by Coding-Doctors** [comment]
Note that clippy is failed in the build due to errors in the code, it's currently set to fail even on warnings. Its not part of the regular build matrix in case of clippy nightly breakage.

**Comment by too-r** [comment]
what does this actually do to help testing?

**Comment by Coding-Doctors** [comment]
By having chippy fail on warnings, it allows you to more easily see when warnings pop up, so you can I know if changes are needed at a glance. Though looking at the output I may need to do something different with it, as it stands now it's not showing the errors that the clippy lints should be showing.

**Comment by Coding-Doctors** [comment]
I've fixed the lints so that the clippy ones will actually run on the travis clippy build, this isn't all notes, but just those that aren't prone to false postives (and might be considered a bit overly aggressive)  (see second bullet point of [the clippy readme](https://github.com/rust-lang-nursery/rust-clippy#allowingdenying-lints))

**Pull request merged**
